<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" src="/js/jquery-ui.js"></script>
		<script type="text/javascript" src="/js/questionary/items.js"></script>
		<link rel="stylesheet" type="text/css" href="/css/styles.css" />
		<link rel="stylesheet" type="text/css" href="/css/questionary.css" />
		<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" />
		<!--[if IE]><link rel="stylesheet" type="text/css" href="/css/fucking.ie.css" /><![endif]-->
		<title>Dotazníky - G U A R D 7, v.o.s.</title>
	</head>
	<body>
		<div id="wrapper">
			<div id="head">
				<img src="/images/logo1.gif" />
			</div>
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>
