<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" src="/js/jquery-ui.js"></script>
		<script type="text/javascript" src="/js/questionary/items.js"></script>
		<link rel="stylesheet" type="text/css" href="/css/questionary.css" />
		<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" />
	</head>
	<body>
		<!-- <script type="text/javascript" src="/js/test.js"></script>  --> 
		<?php echo $this->layout()->content; ?>
		<form id="content">
			
		</form><br /><br />
		<form id="content2">
			
		</form>
	</body>
</html>
