<script type="text/javascript">
<?php
echo "var QDATA=" . Zend_Json::encode($this->questionary->toArray());
?>
</script>
<div class="questionary-container">
	<form action="/client/save" method="post" class="questionary-form" id="<?php echo $this->formId; ?>">
		<div id="questionary-content"></div>
		<div id="questionary-controll">
			<p>
				<?php 
				echo $this->formSubmit("questionary-submit", "Odeslat dotazník");
				echo $this->formHidden("questionary-filled-key", $this->trans->key);
				?>
			</p>
		</div>
	</form>
</div>
<script type="text/javascript" src="/js/client/fill.js"></script>